name: ci

on: [push]

permissions:
  contents: read

env:
  NODE_VERSION: "22.13.0"

jobs:
  checkers-web:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./checkers-web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'
          cache-dependency-path: 'checkers-web/yarn.lock'

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Build code
        run: yarn build

  ml-core:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./ml-core
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Install packages
        run: uv sync --python 3.13

      - name: Lint
        run: uv run black . --check