name: ci

on: [push]

permissions:
  contents: read

env:
  NODE_VERSION: "24.14.0"

jobs:
  checkers-web:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./checkers-web
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: yarn install --immutable

      - name: Lint code
        run: yarn lint

      - name: Build code
        run: yarn build

  ml-core:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./ml-core
    steps:
      - uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Install packages
        run: uv sync --python 3.13

      - name: Lint
        run: uv run black . --check